name: clean packages

on:
  schedule:
    - cron: '30 1 * * 1'

jobs:
  clean_packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20 # v4
        with:
          package-name: errbot
          package-type: container
          # do not delete releases
          ignore-versions: '^\d+\.\d+\.\d+$'
