name: clean packages

on:
  schedule:
    - cron: '30 1 * * 1'

jobs:
  clean_packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: errbot
          package-type: container
          # do not delete releases
          ignore-versions: '^\d+\.\d+\.\d+$'
