name: build docker image

on:
  push:
#    branches:
#      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1

    - name: build and push image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: image-name
        registry: ghcr.io
        githubOrg: override-org # optional
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
