---
name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  main:
    name: Lint PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@95af3b9b31c4e8a73ba942334cfdac3cdf7618c7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          # Configure which scopes are allowed.
          # deps - dependency updates
          # master - for release-please (scope used for releases)
          scopes: |
            deps
            master
          requireScope: false
          # ensure that the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
