---
name: Auto update release version

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - release-please--branches--master
  
jobs:
  set-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4 # ratchet:actions/checkout@v3
      - name: Set release version
        id: set_release_version
        env:
          HEAD_COMMIT_TITLE: ${{ github.event.head_commit.message }}
        run: |
          file=$(find . -name "version.py")
          version_number=${HEAD_COMMIT_TITLE##* }
          sed -i "s/^VERSION .*$/VERSION = \"$version_number\"/" $file
      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        with:
          commit_message: set release version
